// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: relay.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayNetwork int32

const (
	RelayNetwork_TCP RelayNetwork = 0
	RelayNetwork_UDP RelayNetwork = 1
)

// Enum value maps for RelayNetwork.
var (
	RelayNetwork_name = map[int32]string{
		0: "TCP",
		1: "UDP",
	}
	RelayNetwork_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
	}
)

func (x RelayNetwork) Enum() *RelayNetwork {
	p := new(RelayNetwork)
	*p = x
	return p
}

func (x RelayNetwork) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayNetwork) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[0].Descriptor()
}

func (RelayNetwork) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[0]
}

func (x RelayNetwork) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayNetwork.Descriptor instead.
func (RelayNetwork) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

type RelayClose int32

const (
	RelayClose_CLOSE_FULL  RelayClose = 0
	RelayClose_CLOSE_READ  RelayClose = 1
	RelayClose_CLOSE_WRITE RelayClose = 2
)

// Enum value maps for RelayClose.
var (
	RelayClose_name = map[int32]string{
		0: "CLOSE_FULL",
		1: "CLOSE_READ",
		2: "CLOSE_WRITE",
	}
	RelayClose_value = map[string]int32{
		"CLOSE_FULL":  0,
		"CLOSE_READ":  1,
		"CLOSE_WRITE": 2,
	}
)

func (x RelayClose) Enum() *RelayClose {
	p := new(RelayClose)
	*p = x
	return p
}

func (x RelayClose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayClose) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[1].Descriptor()
}

func (RelayClose) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[1]
}

func (x RelayClose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayClose.Descriptor instead.
func (RelayClose) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

type RelayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*RelayRequest_Start
	//	*RelayRequest_Data
	//	*RelayRequest_Close
	Message isRelayRequest_Message `protobuf_oneof:"message"`
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (m *RelayRequest) GetMessage() isRelayRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *RelayRequest) GetStart() *RelayRequestStart {
	if x, ok := x.GetMessage().(*RelayRequest_Start); ok {
		return x.Start
	}
	return nil
}

func (x *RelayRequest) GetData() *RelayData {
	if x, ok := x.GetMessage().(*RelayRequest_Data); ok {
		return x.Data
	}
	return nil
}

func (x *RelayRequest) GetClose() RelayClose {
	if x, ok := x.GetMessage().(*RelayRequest_Close); ok {
		return x.Close
	}
	return RelayClose_CLOSE_FULL
}

type isRelayRequest_Message interface {
	isRelayRequest_Message()
}

type RelayRequest_Start struct {
	Start *RelayRequestStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type RelayRequest_Data struct {
	Data *RelayData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type RelayRequest_Close struct {
	Close RelayClose `protobuf:"varint,3,opt,name=close,proto3,enum=relay.RelayClose,oneof"`
}

func (*RelayRequest_Start) isRelayRequest_Message() {}

func (*RelayRequest_Data) isRelayRequest_Message() {}

func (*RelayRequest_Close) isRelayRequest_Message() {}

type RelayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*RelayResponse_Data
	//	*RelayResponse_Close
	Message isRelayResponse_Message `protobuf_oneof:"message"`
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (m *RelayResponse) GetMessage() isRelayResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *RelayResponse) GetData() *RelayData {
	if x, ok := x.GetMessage().(*RelayResponse_Data); ok {
		return x.Data
	}
	return nil
}

func (x *RelayResponse) GetClose() RelayClose {
	if x, ok := x.GetMessage().(*RelayResponse_Close); ok {
		return x.Close
	}
	return RelayClose_CLOSE_FULL
}

type isRelayResponse_Message interface {
	isRelayResponse_Message()
}

type RelayResponse_Data struct {
	Data *RelayData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type RelayResponse_Close struct {
	Close RelayClose `protobuf:"varint,2,opt,name=close,proto3,enum=relay.RelayClose,oneof"`
}

func (*RelayResponse_Data) isRelayResponse_Message() {}

func (*RelayResponse_Close) isRelayResponse_Message() {}

type RelayRequestStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network RelayNetwork `protobuf:"varint,1,opt,name=network,proto3,enum=relay.RelayNetwork" json:"network,omitempty"`
	Address string       `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RelayRequestStart) Reset() {
	*x = RelayRequestStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayRequestStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequestStart) ProtoMessage() {}

func (x *RelayRequestStart) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequestStart.ProtoReflect.Descriptor instead.
func (*RelayRequestStart) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *RelayRequestStart) GetNetwork() RelayNetwork {
	if x != nil {
		return x.Network
	}
	return RelayNetwork_TCP
}

func (x *RelayRequestStart) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RelayData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RelayData) Reset() {
	*x = RelayData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayData) ProtoMessage() {}

func (x *RelayData) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayData.ProtoReflect.Descriptor instead.
func (*RelayData) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3}
}

func (x *RelayData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_relay_proto protoreflect.FileDescriptor

var file_relay_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72,
	0x65, 0x6c, 0x61, 0x79, 0x22, 0x9e, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x6c,
	0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65,
	0x6c, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x29, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x6d, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x6c,
	0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x29,
	0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x5c, 0x0a, 0x11, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52,
	0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x1f, 0x0a, 0x09, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x2a, 0x20, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x55, 0x44, 0x50, 0x10, 0x01, 0x2a, 0x3d, 0x0a, 0x0a, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x46, 0x55, 0x4c,
	0x4c, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x52, 0x45, 0x41,
	0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x57, 0x52, 0x49,
	0x54, 0x45, 0x10, 0x02, 0x32, 0x3f, 0x0a, 0x05, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x36, 0x0a,
	0x05, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x13, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x52,
	0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x72, 0x65,
	0x6c, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x73, 0x6e, 0x65, 0x77, 0x6d, 0x61, 0x6e, 0x2f, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x66, 0x6c, 0x75, 0x78, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x72, 0x65, 0x6c, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData = file_relay_proto_rawDesc
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(file_relay_proto_rawDescData)
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_relay_proto_goTypes = []interface{}{
	(RelayNetwork)(0),         // 0: relay.RelayNetwork
	(RelayClose)(0),           // 1: relay.RelayClose
	(*RelayRequest)(nil),      // 2: relay.RelayRequest
	(*RelayResponse)(nil),     // 3: relay.RelayResponse
	(*RelayRequestStart)(nil), // 4: relay.RelayRequestStart
	(*RelayData)(nil),         // 5: relay.RelayData
}
var file_relay_proto_depIdxs = []int32{
	4, // 0: relay.RelayRequest.start:type_name -> relay.RelayRequestStart
	5, // 1: relay.RelayRequest.data:type_name -> relay.RelayData
	1, // 2: relay.RelayRequest.close:type_name -> relay.RelayClose
	5, // 3: relay.RelayResponse.data:type_name -> relay.RelayData
	1, // 4: relay.RelayResponse.close:type_name -> relay.RelayClose
	0, // 5: relay.RelayRequestStart.network:type_name -> relay.RelayNetwork
	2, // 6: relay.Relay.Relay:input_type -> relay.RelayRequest
	3, // 7: relay.Relay.Relay:output_type -> relay.RelayResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayRequestStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_relay_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RelayRequest_Start)(nil),
		(*RelayRequest_Data)(nil),
		(*RelayRequest_Close)(nil),
	}
	file_relay_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*RelayResponse_Data)(nil),
		(*RelayResponse_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relay_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		EnumInfos:         file_relay_proto_enumTypes,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_rawDesc = nil
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
