apiVersion: flux.local/v1alpha1
kind: Config
defaultCluster: minikube
clusters:
  - name: minikube
    minikube:
      profile: dev1
      registryAliases:
        - example.invalid
      addons:
        - ingress
    relay:
      enabled: true
deployments:
  - name: simple
    images:
      - image: example.invalid/hello
        context: hello
    steps:
      - name: podinfo
        helm:
          repo: https://stefanprodan.github.io/podinfo
          chart: podinfo
          version: '6.5.*'
          namespace: podinfo
          values:
            replicaCount: 1
      - name: core
        kustomize:
          context: deploy
          namespace: demo
    portForward:
      - kind: Service
        namespace: ingress-nginx
        name: ingress-nginx-controller
        port: 80
        localPort: 8080
      - kind: Deployment
        namespace: demo
        name:  the-deployment
        port: 8080
        localPort: 8081
