apiVersion: flux.local/v1alpha1
kind: Config
defaultCluster: minikube
clusters:
  - name: minikube
    minikube:
      profile: dev1
      portForward: true
      registryAliases:
        - example.invalid
deployments:
  - name: simple
    images:
      - image: example.invalid/hello
        context: hello
    steps:
      - name: podinfo
        helm:
          repo: https://stefanprodan.github.io/podinfo
          chart: podinfo
          version: '6.5.*'
          namespace: podinfo
          values:
            replicaCount: 1
      - name: core
        kustomize:
          context: deploy
          namespace: demo
